name: '🔔 새로운 이슈 생성'
description: '프로젝트 개선을 위한 새로운 이슈를 등록합니다.'
labels: ['✨ enhancement', '📌 todo']
title: '🔥 이슈 제목을 명확하게 작성해주세요'
body:
  - type: input
    id: overview
    attributes:
      label: '📝 이슈 개요 (Overview)'
      description: |
        이 이슈가 해결하고자 하는 문제 또는 구현하려는 목적을 한 문장으로 요약해주세요.
        *팀원이 1초 만에 이해할 수 있을 정도로 명확하고 간결하게!*
      placeholder: '예: 이벤트 생성 화면에서 날짜 선택 UX 개선 필요'
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: '🎯 배경 & 필요성 (Motivation)'
      description: |
        왜 이 이슈가 필요한가요?  
        이 변경이 사용자 경험, 유지보수성, 성능 등에 어떤 가치를 제공하나요?  
        **면접관·협업자가 읽어도 설득될 정도로 작성하면 좋습니다.**
      placeholder: |
        - 기존 기능의 불편한 점 또는 개선 이유
        - 해결하지 않았을 경우 예상되는 문제
        - 개선 후 기대되는 효과
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '🛠️ 할 일 (Task Breakdown)'
      description: |
        실제 구현에 필요한 작업을 단계별로 작성해주세요.  
        *체크리스트는 코드 리뷰어가 보기에 가장 좋습니다.*
      value: |
        - [ ] 요구사항 분석
        - [ ] UI/UX 구성 혹은 API 스펙 정의
        - [ ] 기능 개발
        - [ ] 테스트 및 검증
        - [ ] 문서 업데이트
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: '🚦 우선순위 (Priority)'
      description: '작업의 시급성과 중요도를 선택해주세요.'
      options:
        - 🟥 High (즉시 처리 필요)
        - 🟧 Medium (가급적 빠른 시일 내 처리)
        - 🟩 Low (여유 있을 때 처리)
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: '📌 완료 기준 (Acceptance Criteria)'
      description: |
        이 이슈가 “완료되었다”고 판단할 수 있는 기준을 작성해주세요.  
        QA 또는 본인이 체크할 수 있는 수준으로 상세할수록 좋습니다.
      placeholder: |
        - 기능이 명세대로 동작한다.
        - 오류 로그가 발생하지 않는다.
        - UX 시나리오 테스트에서 모든 케이스 통과.
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: '📎 참고 자료 (Reference)'
      description: |
        스크린샷, 링크, API 문서, 관련 이슈 등  
        개발에 도움이 되는 모든 맥락을 자유롭게 첨부해주세요.
      placeholder: '링크 / 이미지 / 로그 / 흐름도 등'
    validations:
      required: false
